# Generated by Django 5.1 on 2024-09-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0010_feedback_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='User_name',
        ),
        migrations.AddField(
            model_name='feedback',
            name='Name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='feedback_images/'),
        ),
    ]
