# Generated by Django 5.1 on 2024-10-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0015_alter_order_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pincode',
            field=models.CharField(default='000000', max_length=10),
        ),
    ]
