# Generated by Django 5.1 on 2024-09-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=55)),
                ('Email', models.EmailField(max_length=55)),
                ('Number', models.IntegerField()),
                ('Date', models.DateField()),
                ('Person', models.IntegerField()),
            ],
        ),
    ]
